#! /bin/sh

#-------------------------------------------------------------
#           Author: Steven Spasbo
#-------------------------------------------------------------
if [[ $SHELL == *zsh ]]; then
  export RC_FILE="$HOME/.zshrc"
else
  export RC_FILE="$HOME/.bashrc"
fi

alias rc='$EDITOR $RC_FILE'

#-------------------------------------------------------------
# Command alts
#-------------------------------------------------------------

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
  if [ -s "$HOME/.dircolors" ]; then
    eval $( dircolors -b "$HOME/.dircolors" )
  fi
else # macOS `ls`
  colorflag="-G"
  export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

alias ll='ls -lAFhG'

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'

alias psa='ps aux'
alias psg="ps aux | grep "

alias df='df -h'
alias du='du -h -c'

alias ping='ping -c 5'

alias branches="git branch -a | grep -i "

#-------------------------------------------------------------
# System stuff
#-------------------------------------------------------------
alias reload='clear && exec $SHELL'
alias hist='history | grep -i $*'
alias cal='cal | grep --before-context 6 --after-context 6 --color -e " $(date +%e)" -e "^$(date +%e)"'

alias emacs='emacs -nw'

#-------------------------------------------------------------
# Shortcuts and directory stuff
#-------------------------------------------------------------
alias ..='cd ..'
alias ...='cd ../..'
alias downloads='cd ~/Downloads'
alias desktop='cd ~/Desktop'

#-------------------------------------------------------------
# Personalized shortcuts
#-------------------------------------------------------------
alias nethack='telnet nethack.alt.org'


#-------------------------------------------------------------
# HTTP
#-------------------------------------------------------------
alias get='curl -s -XGET'
alias post='curl -s -XPOST'
alias put='curl -s -XPUT'
alias delete='curl -s -XDELETE'

alias sniff="sudo ngrep -d 'en0' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
function removeFromPath() {
  export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")
}

function cleanpath() {
  if [ -n "$PATH" ]; then
    old_PATH=$PATH:; PATH=
    while [ -n "$old_PATH" ]; do
      x=${old_PATH%%:*}       # the first remaining entry
      case $PATH: in
        *:"$x":*) ;;         # already there
        *) PATH=$PATH:$x;;    # not there yet
      esac
      old_PATH=${old_PATH#*:}
    done
    PATH=${PATH#:}
    unset old_PATH x
  fi
}

[[ -s "$HOME/.aliases.local" ]]  && . "$HOME/.aliases.local"
