#!/usr/bin/env bash

#-------------------------------------------------------------
#           Author: Steven Spasbo
#-------------------------------------------------------------

#-------------------------------------------------------------
# Environment stuff
#-------------------------------------------------------------

if [[ -L ~/.bashrc ]]; then
  case "$(uname -s)" in
    Darwin)
      export DOTFILE_REPO=`dirname $(greadlink -f ~/.bashrc)`
      ;;
    Linux)
      export DOTFILE_REPO=`dirname $(readlink -f ~/.bashrc)`
      ;;
    *)
  esac
fi

source ~/.aliases

#-------------------------------------------------------------
# History stuff
#-------------------------------------------------------------
shopt -s histappend # Append to history file instead of overwriting

#-------------------------------------------------------------
# Prompt
#-------------------------------------------------------------
source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
source $(brew --prefix)/etc/bash_completion

export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\[$(tput bold)\]\[$(tput setaf 7)\][\[$(tput setaf 4)\]\u\[$(tput setaf 5)\]@\[$(tput setaf 6)\]\h: \[$(tput setaf 2)\]\w\[$(tput setaf 7)\]]$(__git_ps1 " (%s)")\n\[$(tput setaf 2)\]λ \[$(tput sgr0)\]'
