#!/usr/bin/env bash

[ -s $HOME/.exports ] && . $HOME/.exports
[ -s $HOME/.aliases ] && . $HOME/.aliases

# Enable completions
if [ "$IS_MAC" = true ] && [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

source "$HOME/.bashrc"
