#! /usr/bin/env sh

case "$(uname -s)" in
  Darwin)
    export IS_MAC=true
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
    ;;
  Linux)
    export IS_LINUX=true
    ;;
  *)
    ;;
esac

export EDITOR=emacs
export GIT_EDITOR='emacs -nw'

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#-------------------------------------------------------------
# History stuff
#-------------------------------------------------------------
export HISTCONTROL=ignoreboth:ignoredups:erasedups # Ignore lines that are duplicates or begin with space
export HISTSIZE=100000
export HISTFILESIZE=100000
export SAVEHIST=100000
export HISTFILE=~/.history
export HISTFORMAT='%F %T '
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

export CLICOLOR=1

#-------------------------------------------------------------
# Colorful man pages
#-------------------------------------------------------------
export PAGER=less
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline
#-------------------------------------------------------------
# ssh
#-------------------------------------------------------------
export SSH_KEY_PATH="~/.ssh/rsa_id"

if brew --prefix coreutils > /dev/null 2>&1; then
  export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH
  export MANPATH=$(brew --prefix coreutils)/libexec/gnuman:$MANPATH
fi
