#! /usr/bin/env sh

#-------------------------------------------------------------
# System stuff
#-------------------------------------------------------------

case "$(uname -s)" in
  Darwin)
    export IS_MAC=true
    export BROWSER='open'

    if command -v brew > /dev/null; then
      export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"

      # GNU coreutils
      export CORE_UTILS=$(brew --prefix coreutils) > /dev/null 2>&1
      if [ -n $CORE_UTILS ]; then
        export PATH="$CORE_UTILS/libexec/gnubin:$PATH"
        export MANPATH="$CORE_UTILS/libexec/gnuman:$MANPATH"
      fi

      if command -v fzf > /dev/null; then
        source "$(brew --prefix fzf)/shell/key-bindings.zsh"
      fi

    fi
    ;;
  *)
    ;;
esac

export EDITOR="emacs -nw"
export GIT_EDITOR="emacs -nw"
export PAGER=less

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

export TZ="America/Los_Angeles"

#-------------------------------------------------------------
# History stuff
#-------------------------------------------------------------
export HISTCONTROL=ignoreboth:ignoredups:erasedups # Ignore lines that are duplicates or begin with space
export HISTSIZE=100000
export HISTFILESIZE=100000
export SAVEHIST=100000
export HISTFILE=~/.history
export HISTFORMAT='%F %T '
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Environment specific stuff.
[[ -s "$HOME/.exports.local" ]] && . "$HOME/.exports.local"

# PATH
[[ -d "$HOME/.local/bin" ]] && PATH="$HOME/.local/bin:$PATH"
[[ -d "$HOME/.bin" ]] && PATH="$HOME/.bin:$PATH"
[[ -d "$HOME/bin" ]] && PATH="$HOME/bin:$PATH"

[[ -d "/opt/java/Contents/Home/bin" ]] && PATH="/opt/java/Contents/Home/bin:$PATH"
