#! /usr/bin/env sh

#-------------------------------------------------------------
# System stuff
#-------------------------------------------------------------
case "$(uname -s)" in
  Darwin)
    export IS_MAC=true
    export BROWSER='open'

    if command -v brew > /dev/null; then
      export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"

      if [[ $SHELL == *"bash"* ]]; then
        BREW_PREFIX=$(brew --prefix)
        source "$BREW_PREFIX/etc/bash_completion"
        source "$BREW_PREFIX/etc/bash_completion.d/git"
      fi

      # GNU coreutils
      export CORE_UTILS=$(brew --prefix coreutils) > /dev/null 2>&1
      if [ -n $CORE_UTILS ]; then
        export PATH="$CORE_UTILS/libexec/gnubin:$PATH"
        export MANPATH="$CORE_UTILS/libexec/gnuman:$MANPATH"
      fi

    fi
    ;;
  Linux)
    export IS_LINUX=true
    ;;
  *)
    ;;
esac

export EDITOR=emacs

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

export TZ="America/Los_Angeles"

#-------------------------------------------------------------
# History stuff
#-------------------------------------------------------------
export HISTCONTROL=ignoreboth:ignoredups:erasedups # Ignore lines that are duplicates or begin with space
export HISTSIZE=100000
export HISTFILESIZE=100000
export SAVEHIST=100000
export HISTFILE=~/.history
export HISTFORMAT='%F %T '
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

export CLICOLOR=1

#-------------------------------------------------------------
# Less
#-------------------------------------------------------------
export PAGER=less

# export LESS='-MR'
# export LESSOPEN='| ~/.lessfilter %s'

#-------------------------------------------------------------
# ssh
#-------------------------------------------------------------
export SSH_KEY_PATH="~/.ssh/rsa_id"
export DO_TOKEN=e0107615e7e0a6077218eba2e80f9372a7905fd38c6becad392bdcef5d0b7478
