"""""""""""""""""""""""""""""""""""""""""""
"           Author: Steven Spasbo         "
"""""""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""""""
" Plugins
"""""""""""""""""""""""""""""""""""""""""""
try
  execute pathogen#infect()
  autocmd VimEnter * NERDTree
  autocmd VimEnter * wincmd p
  autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()
catch
endtry
" Close all open buffers on entering a window if the only
" buffer that's left is the NERDTree buffer
function! s:CloseIfOnlyNerdTreeLeft()
  if exists("t:NERDTreeBufName")
    if bufwinnr(t:NERDTreeBufName) != -1
      if winnr("$") == 1
        q
      endif
    endif
  endif
endfunction

"""""""""""""""""""""""""""""""""""""""""""
" Misc vim settings
"""""""""""""""""""""""""""""""""""""""""""
set nocompatible " Uses vim settings instead of vi settings
filetype on
filetype plugin on
set number " Enables line numbers
"set mouse=a " Enable mouse
set ruler " Show position
set showmode

"""""""""""""""""""""""""""""""""""""""""""
" Text, tabs, indentds
"""""""""""""""""""""""""""""""""""""""""""
" 1 tab == 2 spaces
set tabstop=2
set shiftwidth=2

set ignorecase " Ignores case while searching
set smartcase " Unless search contains uppercase

filetype indent on " Smart indents
set expandtab " Use spaces instead of tabs
set wrap
set autoindent
set smarttab

"""""""""""""""""""""""""""""""""""""""""""
" Files, undos
"""""""""""""""""""""""""""""""""""""""""""
set noswapfile " Disables swap files
set undolevels=1000 " Updo 1000 changes
set updatecount=100 " Update swapfile after 100 character changes

"""""""""""""""""""""""""""""""""""""""""""
" Color settings
"""""""""""""""""""""""""""""""""""""""""""
set background=dark " For dark terminals
syntax enable " Syntax highlighting
colorscheme molokai
set encoding=utf8
let g:airline_powerline_fonts = 1
let g:airline_theme='light'

"""""""""""""""""""""""""""""""""""""""""""
" Status line
"""""""""""""""""""""""""""""""""""""""""""
set laststatus=2
"set statusline=%F " Full path to file
"set statusline+=%m " Flag if modified
"set statusline+=%h " Help file flag
"set statusline+=%r " Flag [RO] if only read-only
"set statusline+=%y " File type
"set statusline+=%= " Separator
"set statusline+=%c,
"set statusline+=%l/%L " Cursor location
"set statusline+=\ %P " Percent through file

"""""""""""""""""""""""""""""""""""""""""""
" Mappings
"""""""""""""""""""""""""""""""""""""""""""
set backspace=indent,eol,start

