#
# Executes commands at login post-zshrc.
#
# Execute code that does not affect the current session in the background.

{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# For bash / zsh compatability, exports will go in a separate file.
[[ -s "$HOME/.exports" ]] && . "$HOME/.exports"
[[ -s "$HOME/.aliases" ]] && . "$HOME/.aliases"
