#!/usr/bin/env zsh

#
# Author: Steven Spasbo
#
# Next to load is ~/.zlogin

# Set some opts
setopt auto_pushd
setopt cdable_vars
setopt chase_links # chase symlinks
setopt glob_dots # emacs zsh [tab] [tab] -> .zshrc .zprofile .z[a-z]+
setopt auto_list # Automatically expand menu
setopt pushd_to_home

#   zmv [OPTIONS] oldpattern newpattern
# where oldpattern contains parenthesis surrounding patterns which will
# be replaced in turn by $1, $2, ... in newpattern.  For example,
#   zmv '(*).lis' '$1.txt'
autoload zmv

# Suffix's
# alias -s rb=ruby
# alias -s py=python
# alias -s php=php
# alias -s pl=perl
autoload -U zsh-mime-setup
zsh-mime-setup

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export SHELL=zsh

#ZSH_THEME="nick"
ZSH_THEME="agnoster"

DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

ZSH_CUSTOM=$HOME/.zsh-custom # Custom themes and libs

plugins=(colored-man common-aliases)
[[ -s $ZSH_CUSTOM/plugins/zsh-syntax-highlighting ]] && plugins+=(zsh-syntax-highlighting)
# Check for executables
for p (git tmux vagrant grunt composer); do
  if type $p > /dev/null; then
    plugins+=($p)
  fi
done

source $ZSH/oh-my-zsh.sh

# Override oh-my-zsh

# Enable approximate completions
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle -e ':completion:*:approximate:*' max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3)) numeric)'

# Always use menu selection for `cd -`
zstyle ':completion:*:*:cd:*:directory-stack' force-list always
zstyle ':completion:*:*:cd:*:directory-stack' menu yes select

# Pretty messages during pagination
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'

# Verbose completion results
zstyle ':completion:*' verbose true

# Enable menus
zstyle ':completion:*' menu select

# Group items by group
zstyle ':completion:*' group-name ''

# No results; ex:  commandthatdoesntexist[tab]
zstyle ':completion:*:warnings' format '%F{red%}%BNo results'

# Results; Sets formatting of group titles
zstyle ':completion:*' format '%F{yellow}%B---- %d%b'

# Autocorrect
zstyle ':completion:*:corrections' format '%U%F{green}Suggested %d%f%u'

# # Not sure...
# zstyle ':completion:*:descriptions' format $'%{\e[0;31m%}completing %B%d%b%{\e[0m%}'
# Nicer format for completion messages (stolen; still not sure what it does)
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
# # Not sure...
# zstyle ':completion:*:messages' format '%B%U---- %d%u%b'

# zstyle ':completion:*:commands' list-colors '=*=1;32 # For reference
# zstyle ':completion:*:*:*:default' menu yes select # Select item from menu

# kill command completion
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*'   force-list always
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

zstyle ':completion:*:*:*:*:processes' list-colors '=(#b) #([0-9]#) ([\.0-9a-z-]#)*=01;34=0=01'
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,args -w -w"

zstyle ':completion:*' rehash true

# Ignore missing commands
zstyle ':completion:*:functions' ignored-patterns '_*'

# Aliases

alias -g gp=' | grep -i'
alias -g l=' | less'

# Finally

[[ -s $HOME/.aliases ]] && . $HOME/.aliases
[[ -s $HOME/.exports ]] && . $HOME/.exports
