#!/usr/bin/env zsh

#
# Author: Steven Spasbo
#
# Next to load is ~/.zlogin

zmodload zsh/complist
zmodload zsh/terminfo

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.zsh-custom"

autoload -U compinit && compinit
autoload -U colors && colors
autoload -U vcs_info && vcs_info

ZSH_THEME="spasbo"

DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins+=(themes)
plugins+=(history-substring-search zsh-completions)
[[ -d $ZSH_CUSTOM/plugins/zsh-syntax-highlighting ]] && plugins+=(zsh-syntax-highlighting)
[[ -d $ZSH_CUSTOM/plugins/zsh-autopair ]] && plugins+=(zsh-autopair)

# Check for executables
for p (composer pip pyenv aws docker docker-compose); do
  if command -v $p > /dev/null; then
    plugins+=($p)
  fi
done

source "$ZSH/oh-my-zsh.sh"

# Check `zshoptions` man page for more values
setopt ALWAYS_TO_END
setopt AUTO_CD
setopt AUTO_LIST # Automatically expand menu
setopt AUTO_MENU # show completion menu on succesive tab press
setopt AUTO_PUSHD
setopt CDABLE_VARS
setopt CHASE_LINKS # chase symlinks, opposite of CHASE_DOTS
setopt COMPLETE_ALIASES
setopt CORRECT_ALL
setopt EXTENDED_GLOB
setopt GLOB_DOTS # emacs zsh [tab] [tab] -> .zshrc .zprofile .z[a-z]+
setopt IGNOREEOF # Don't kill session with ctrl+D
setopt LIST_PACKED
setopt NO_MENU_COMPLETE
setopt NO_BEEP
setopt PROMPT_SUBST
setopt PUSHD_TO_HOME
setopt PUSHD_SILENT
setopt PUSHD_MINUS # This inverts the +/- operators.
setopt INTERACTIVE_COMMENTS # Recognize comments
unsetopt FLOWCONTROL
unsetopt MENU_COMPLETE # do not autoselect the first completion entry

unsetopt EXTENDED_HISTORY # Don't save timestamp info with history

nocorrect which

# Load all custom zsh configurations, ignoring temp files.
if [[ -d "$ZSH_CUSTOM/config" ]]; then
  for f in $(ls $ZSH_CUSTOM/config/[^.#]*.zsh); do
    source $f
  done
fi

zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -a zsh/zprof zprof
zmodload -ap zsh/mapfile mapfile

autoload -U tetriscurses # Slacker
autoload zmv # Move files using glob, Ex: zmv '(*).lis' '$1.txt'
autoload -U zsh-mime-setup # Set file suffixes.
zsh-mime-setup
if command -v vlc > /dev/null; then
  alias -s mp4=vlc
fi

if [[ -n $HELPDIR ]]; then
  unalias run-help 2> /dev/null
  autoload run-help
  alias help=run-help
fi

# Global aliases
alias -g G=' | grep -i'
alias -g L=' | less'

[[ -s $HOME/.aliases ]] && . $HOME/.aliases

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--reverse --border --exact --height=50%'
# export FZF_ALT_C_COMMAND='fd --type directory'
# export FZF_CTRL_T_COMMAND="mdfind -onlyin . -name ."



zman() {
  PAGER="less -g -s '+/^       "$1"'" man zshall
}
