#!/usr/bin/env zsh

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
ZSH_HIGHLIGHT_MAXLENGTH=300


HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=magenta,fg=white,bold'
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='bg=red,fg=white,bold'
HISTORY_SUBSTRING_SEARCH_GLOBBING_FLAGS='i'

# typeset -A ZSH_HIGHLIGHT_STYLES
# : ${ZSH_HIGHLIGHT_STYLES[alias]:=fg=blue}
# : ${ZSH_HIGHLIGHT_STYLES[builtin]:=fg=141}
# : ${ZSH_HIGHLIGHT_STYLES[globbing]:=fg=105}
